[tool.poetry]
name = "amhelpers"
version = "0.1.0"
description = "A collection of handy utilities."
authors = ["Anton Matsson"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"

[tool.poetry.dev-dependencies]
myst-nb = {version = "^0.15.0", python = "^3.9"}
sphinx-autoapi = "^1.8.4"
sphinx-rtd-theme = "^1.0.0"
python-semantic-release = {version = "^7.28.1", python = "^3.9"}
pytest = "^7.1.2"

[tool.semantic_release]
version_variable = "pyproject.toml:version"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
